### ISSUE TITLE
Organización de tareas

### ISSUE THREAD

**Issue by xXcarlos117Xx2** [4GeeksAcademy/sp72-final-project-g1#30]
# Organización de tareas

Este issue debe estar listo antes del despliegue del sitio web. No hay excusas. Para ello, organizaremos las tareas de manera un poco diferente a como lo hemos hecho hasta ahora.
### Milestones:
![image](https://github.com/user-attachments/assets/f66a8df2-de23-4e43-ba57-014c4d51d47b)

### Ramas:
- Usaremos una rama para cada persona. La rama se nombrará como `nombre-deploy-#1`. Por ejemplo, mi rama sería `carlos-deploy-#1`. En esa rama, vamos a modificar todos los archivos que consideremos necesarios.
  - Es importante comunicarse con el equipo sobre lo que están haciendo para evitar trabajar en lo mismo. Si es necesario crear más **issues**, está bien.
  - Esto es para evitar la necesidad de crear diferentes ramas al manejar archivos distintos (porque lo vamos a necesitar).

### Documentación:
<s>
- La documentación de la API se puede encontrar aquí.

  - Si tocas las rutas o endpoints, **por favor actualiza la documentación y deja una nota en el pull request**.
</s>

### Pull Request a `Main`
- El pull request a `Main` será realizado por @FcoJCarrillo cuando se cumplan los requisitos mínimos. Este pull request es importante, por lo que todos deben revisar el código antes de aceptarlo. Si se nota algo, por favor deja un comentario en este issue tracker con el siguiente formato:

```md
# Issue: [Nombre del issue]
- Importancia: [Importante | Bug | Menor | Estilo]
- Descripción: [Descripción]
- Archivo que necesita ser añadido/editado: [Nombre del archivo O Dejar en blanco]
- ¿Sabes cómo solucionarlo? [Sí | No]
```

## Vistas requeridas para el despliegue:
- [x] #32
- [x] #31
- [x] #60
- [x] - Profile
- [x] - Game Details
- [ ] - Game list

## Solo si hay tiempo
- [ ] - Buscador
  - [ ] - Backend
  - [ ] - Frontend
- [x] - Panel de admin `Hay que desarrollar`

## Funcionalidades que los usuarios pueden hacer:
- [x] - Registrarse en el sitio web
- [x] - Iniciar sesión en el sitio web
- [ ] - Ver su perfil, editarlo y eliminarlo
- [ ] - Pagar por premium

## Solo si hay tiempo
- [ ] - Buscar un juego
- [x] - Buscar por plataformas
- [ ] - Buscar por genero
